grid_search:
  class: RandomizedSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3

model_selection:
  module_0:
    class: XGBClassifier
    module: xgboost
    params:
      criterion: squared_error
    search_param_grid:
      n_estimators:
        - 100

  module_1:
    class: GradientBoostingClassifier
    module: sklearn.ensemble
    search_param_grid:
      n_estimators:
        - 100
