
Numerical_features:
  - forecast_3_month: float64
  - forecast_6_month: float64
  - forecast_9_month: float64
  - in_transit_qty: float64
  - lead_time: float64
  - local_bo_qty: float64
  - min_bank: float64
  - national_inv: float64
  - perf_12_month_avg: float64
  - perf_6_month_avg: float64
  - pieces_past_due: float64
  - sales_1_month: float64
  - sales_3_month: float64
  - sales_6_month: float64
  - sales_9_month: float64

Categorical_features:
  - deck_risk: object
  - sku: object
  - stop_auto_buy: object
  - ppap_risk: object
  - rev_stop: object
  - potential_issue: object
  - oe_constraint: object

Target_column:
  - went_on_backorder: object

Target_column_Name: went_on_backorder